sudo: required

services:
  - docker

language: python
python:
  - "2.7"
 
script:
  - docker-compose build
  - docker-compose run --rm weblate migrate --noinput
  - docker-compose run --rm weblate collectstatic --noinput
  - docker-compose run --rm weblate createadmin
  - docker-compose run -e WEBLATE_LOGLEVEL=CRITICAL --rm weblate test --noinput weblate.accounts weblate.trans weblate.lang weblate.api
  - docker-compose start
  - docker-compose stop
  - docker-compose start
  - docker-compose stop
