version: '2'

services:
  weblate:
    build: weblate
    links:
      - database
      - cache
    expose:
      - "8000"
    volumes:
      - /srv/docker-state/weblate/weblate/rootfs/app/data:/app/data
      - /srv/docker-state/weblate/weblate/rootfs/home/weblate:/home/weblate
    env_file:
      - ./weblate/environment
      - ./weblate/environment.proxy
    networks:
      - frontend
      - backend
    depends_on:
      - database
      - cache
    restart: always
  database:
    # You can change used database here:
    image: postgres:9.4
    expose: ["5432"]
    volumes:
    #  - ./weblate/mysql-charset.conf:/etc/mysql/conf.d/charset.cnf
      - /srv/docker-state/weblate/postgres/rootfs/var/lib/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - ./weblate/environment
    networks:
      - backend
    restart: always
  cache:
    image: memcached:1.4
    networks:
      - backend
    restart: always

networks:
  frontend:
    external:
      name: nginx_default
  backend:
    driver: bridge
